#!/bin/sh

# Make root read/write
mount -o remount,rw /

# Check if files already replaced
if [ ! -f /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.palm.browserbookmarks.old ];
then
	# Back up original perms
	mv /etc/palm/db/permissions/com.palm.browserbookmarks /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.palm.browserbookmarks.old
	mv /etc/palm/db/permissions/com.palm.browserhistory /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.palm.browserhistory.old

	# Move new perms
	cp /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.junoavalon.isisprebrowserbookmarks /etc/palm/db/permissions/com.junoavalon.isisprebrowserbookmarks
	cp /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.junoavalon.isisprebrowserhistory /etc/palm/db/permissions/com.junoavalon.isisprebrowserhistory
	cp /media/cryptofs/apps/usr/palm/applications/com.junoavalon.app.isisprebrowser/db/permissions/com.junoavalon.isisprebrowserhistory /etc/palm/db/permissions/com.junoavalon.isisprebrowserhistory

	luna-send -n 1 palm://com.palm.configurator/run '{"types":["dbpermissions"]}'
fi

exit 0
